# Generated by Django 2.1.3 on 2018-11-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_myuser_koop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='phone',
        ),
    ]
