# Generated by Django 2.1.3 on 2018-11-06 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_myuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='koop',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Koop'),
        ),
    ]
