# Generated by Django 2.1.3 on 2018-11-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
